# Generated by Django 4.0 on 2024-06-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('M', 'Male'), ('F', 'Female'), ('F', 'CD_TV'), ('F', 'TV_TS'), ('MF', 'Couple MF'), ('SR', 'Couple FF')], default='', max_length=2),
        ),
    ]
