# Generated by Django 4.0 on 2024-06-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('ST', 'Straight'), ('BI', 'Bisexial'), ('BC', 'Bi Curious'), ('BO', 'Orally Bi'), ('BP', 'Playfully Bi'), ('G', 'Gay'), ('L', 'Lesbian')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexuality2',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('ST', 'Straight'), ('BI', 'Bisexial'), ('BC', 'Bi Curious'), ('BO', 'Orally Bi'), ('BP', 'Playfully Bi'), ('G', 'Gay'), ('L', 'Lesbian')], default='', max_length=2),
        ),
    ]
