# Generated by Django 4.0 on 2024-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_username_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
