# Generated by Django 4.0 on 2024-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('SM', 'Single Male'), ('SF', 'Single Female'), ('CD/TV', 'CD_TV'), ('TV/TS', 'TV_TS'), ('MF Couple', 'Couple MF'), ('Couple FF', 'Couple FF')], default='', max_length=10),
        ),
    ]
