# Generated by Django 4.0 on 2024-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profile_cover_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
