# Generated by Django 4.0 on 2024-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('Straight', 'Straight'), ('Bisexual', 'Bisexual'), ('Bicurious', 'Bicuriuos'), ('Orally Bi', 'Orally Bi'), ('Bi Playful', 'Bi Playful'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexuality2',
            field=models.CharField(blank=True, choices=[('', 'Select Sexuality'), ('Straight', 'Straight'), ('Bisexual', 'Bisexual'), ('Bicurious', 'Bicuriuos'), ('Orally Bi', 'Orally Bi'), ('Bi Playful', 'Bi Playful'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian')], default='', max_length=10, null=True),
        ),
    ]
