# Generated by Django 4.0 on 2024-06-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_dob2_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB2',
            field=models.DateField(null=True),
        ),
    ]
