# Generated by Django 4.0 on 2024-06-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profile_dob_alter_profile_dob2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB2',
            field=models.DateTimeField(null=True),
        ),
    ]
