# Generated by Django 4.0 on 2024-06-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_profile_dob_alter_profile_dob2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('ME OPTION', 'ME CHOICES'), ('Bisexual', 'Bisexual'), ('Bicurious', 'Bicuriuos'), ('Orally Bi', 'Orally Bi'), ('Bi Playful', 'Bi Playful'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian')], default='', max_length=16),
        ),
    ]
