# Generated by Django 4.0 on 2024-06-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height2',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('400', '4ft 0in'), ('41', '4ft 1in'), ('42', '4ft 2in'), ('43', '4ft 3in'), ('44', '4ft 4in'), ('45', '4ft 5in'), ('46', '4ft 6in'), ('47', '4ft 7in'), ('48', '4ft 8in'), ('49', '4ft 9in'), ('48', '4ft 10in'), ('49', '4ft 11in'), ('50', '5ft 0in'), ('51', '5ft 1in'), ('52', '5ft 2in'), ('53', '5ft 3in'), ('54', '5ft 4in'), ('55', '5ft 5in'), ('56', '5ft 6in'), ('57', '5ft 7in'), ('58', '5ft 8in'), ('59', '5ft 9in'), ('510', '5ft 100in'), ('511', '5ft 11in'), ('60', '6ft 0in'), ('61', '6ft 1in'), ('62', '6ft 2in'), ('63', '6ft 3in'), ('64', '6ft 4in'), ('65', '6ft 5in'), ('66', '6ft 6in'), ('67', '6ft 7in'), ('68', '6ft 8in'), ('69', '6ft 9in'), ('610', '6ft 10in'), ('611', '6ft 11in'), ('700', '7ft 0in')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(choices=[('', 'Select Sexuality'), ('400', '4ft 0in'), ('41', '4ft 1in'), ('42', '4ft 2in'), ('43', '4ft 3in'), ('44', '4ft 4in'), ('45', '4ft 5in'), ('46', '4ft 6in'), ('47', '4ft 7in'), ('48', '4ft 8in'), ('49', '4ft 9in'), ('48', '4ft 10in'), ('49', '4ft 11in'), ('50', '5ft 0in'), ('51', '5ft 1in'), ('52', '5ft 2in'), ('53', '5ft 3in'), ('54', '5ft 4in'), ('55', '5ft 5in'), ('56', '5ft 6in'), ('57', '5ft 7in'), ('58', '5ft 8in'), ('59', '5ft 9in'), ('510', '5ft 100in'), ('511', '5ft 11in'), ('60', '6ft 0in'), ('61', '6ft 1in'), ('62', '6ft 2in'), ('63', '6ft 3in'), ('64', '6ft 4in'), ('65', '6ft 5in'), ('66', '6ft 6in'), ('67', '6ft 7in'), ('68', '6ft 8in'), ('69', '6ft 9in'), ('610', '6ft 10in'), ('611', '6ft 11in'), ('700', '7ft 0in')], default='', max_length=16),
        ),
    ]
