# Generated by Django 4.0 on 2024-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_profile_dob2_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('Slim', 'Slim'), ('Athletic', 'Athletic'), ('Curvy', 'Curvy'), ('Dad Bod', 'Dad Bod'), ('Large', 'Large')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_type2',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('Slim', 'Slim'), ('Athletic', 'Athletic'), ('Curvy', 'Curvy'), ('Dad Bod', 'Dad Bod'), ('Large', 'Large')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='drink',
            field=models.CharField(choices=[('', 'Select Option'), ('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often'), ('Vape', 'Vape')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='drink2',
            field=models.CharField(choices=[('', 'Select Option'), ('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often'), ('Vape', 'Vape')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.CharField(choices=[('', 'Select Smoker Type'), ('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often'), ('Vape', 'Vape')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke2',
            field=models.CharField(choices=[('', 'Select Smoker Type'), ('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often'), ('Vape', 'Vape')], default='', max_length=16),
        ),
    ]
