# Generated by Django 5.0.6 on 2024-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_profile_dob_alter_profile_body_type2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
    ]
