# Generated by Django 5.0.6 on 2024-07-16 23:11

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
