# Generated by Django 5.0.6 on 2024-08-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_myimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='headline',
            new_name='status',
        ),
    ]
