# Generated by Django 5.0.6 on 2024-09-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_alter_profile_cover_image_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
