# Generated by Django 5.0.6 on 2024-09-27 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_alter_userlevel_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(default=18)),
                ('age_max', models.IntegerField(default=99)),
                ('men', models.BooleanField(default=0)),
                ('women', models.BooleanField(default=1)),
                ('mf_couple', models.BooleanField(default=1)),
                ('ff_couple', models.BooleanField(default=1)),
                ('cd_tv', models.BooleanField(default=0)),
                ('tg_ts', models.BooleanField(default=0)),
                ('smokers', models.BooleanField(default=0)),
                ('can_travel', models.BooleanField(default=0)),
                ('can_accom', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
