# Generated by Django 5.0.6 on 2024-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_lookingfor_blockedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookingfor',
            name='can_accom',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='can_travel',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='cd_tv',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='men',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='smokers',
            field=models.BooleanField(),
        ),
    ]
