# Generated by Django 5.0.6 on 2024-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_alter_lookingfor_can_accom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookingfor',
            name='tg_ts',
            field=models.BooleanField(),
        ),
    ]
