# Generated by Django 5.0.6 on 2024-09-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_alter_lookingfor_tg_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='outer_postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
