# Generated by Django 5.0.6 on 2024-10-06 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_alter_profile_outer_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
