# Generated by Django 5.0.6 on 2024-10-06 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_profile_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
