# Generated by Django 5.0.6 on 2024-10-08 17:45

import django_resized.forms
import profiles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_alter_profile_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, quality=-1, scale=None, size=[600, 200], upload_to=profiles.models.PathAndRename('profile/cover')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, quality=-1, scale=None, size=[100, 100], upload_to=profiles.models.PathAndRename('profile/avatar')),
        ),
    ]
