# Generated by Django 5.0.6 on 2024-10-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_alter_profile_cover_image_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
