# Generated by Django 5.0.6 on 2024-10-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_remove_userlevel_level_remove_userlevel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookingfor',
            name='age_max',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='age_min',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='can_accom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='can_travel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='cd_tv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='ff_couple',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='men',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='mf_couple',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='smokers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='tg_ts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='women',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
