# Generated by Django 5.0.6 on 2024-10-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_lookingfor_age_max_alter_lookingfor_age_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('Man', 'Single Male'), ('Woman', 'Single Female'), ('CD/TV', 'CD_TV'), ('TV/TS', 'TV_TS'), ('MF Couple', 'Couple MF'), ('Couple FF', 'Couple FF')], default='', max_length=10),
        ),
    ]
