# Generated by Django 5.0.6 on 2024-10-10 01:40

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
