# Generated by Django 5.0.6 on 2024-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_alter_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('Man', 'Single Male'), ('Woman', 'Single Female'), ('CD/TV', 'CD_TV'), ('TV/TS', 'TV_TS'), ('Couple MF', 'Couple MF'), ('Couple FF', 'Couple FF'), ('Couple MM', 'Couple MM')], default='', max_length=10),
        ),
    ]
