# Generated by Django 5.0.6 on 2024-10-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_lookingfor_mm_couple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookingfor',
            name='age_max',
            field=models.IntegerField(blank=True, default=99),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='age_min',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='can_accom',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='can_travel',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='cd_tv',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='ff_couple',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='men',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='mf_couple',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='mm_couple',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='smokers',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='tg_ts',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
