# Generated by Django 5.0.6 on 2024-10-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_alter_lookingfor_age_max_alter_lookingfor_age_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_parties', models.BooleanField(blank=True, null=True)),
                ('anal', models.BooleanField(blank=True, null=True)),
                ('blindfolds', models.BooleanField(blank=True, null=True)),
                ('cross_dressing', models.BooleanField(blank=True, null=True)),
                ('cuckolding', models.BooleanField(blank=True, null=True)),
                ('cybersex', models.BooleanField(blank=True, null=True)),
                ('dogging', models.BooleanField(blank=True, null=True)),
                ('DP', models.BooleanField(blank=True, null=True)),
                ('fisting', models.BooleanField(blank=True, null=True)),
                ('gangbangs', models.BooleanField(blank=True, null=True)),
                ('Group_Sex', models.BooleanField(blank=True, null=True)),
                ('Making_Videos', models.BooleanField(blank=True, null=True)),
                ('Oral', models.BooleanField(blank=True, null=True)),
                ('Phone_Sex', models.BooleanField(blank=True, null=True)),
                ('Rimming', models.BooleanField(blank=True, null=True)),
                ('Role_Play', models.BooleanField(blank=True, null=True)),
                ('Safe_Sex', models.BooleanField(blank=True, null=True)),
                ('Same_Room_Swapping', models.BooleanField(blank=True, null=True)),
                ('Separate_Room_Swapping', models.BooleanField(blank=True, null=True)),
                ('SM', models.BooleanField(blank=True, null=True)),
                ('Soft_Swing', models.BooleanField(blank=True, null=True)),
                ('Spanking', models.BooleanField(blank=True, null=True)),
                ('Swingers_Clubs', models.BooleanField(blank=True, null=True)),
                ('Taking_Photos', models.BooleanField(blank=True, null=True)),
                ('Threesomes', models.BooleanField(blank=True, null=True)),
                ('Toys', models.BooleanField(blank=True, null=True)),
                ('Voyeurism', models.BooleanField(blank=True, null=True)),
                ('Watersports', models.BooleanField(blank=True, null=True)),
                ('Webcams', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
