# Generated by Django 5.0.6 on 2024-10-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='anal',
        ),
        migrations.AddField(
            model_name='interest',
            name='anal_giving',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='anal_receiving',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='pegging_giving',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='pegging_receiving',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='DP',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Group_Sex',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Making_Videos',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Oral',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Phone_Sex',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Rimming',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Role_Play',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='SM',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Safe_Sex',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Same_Room_Swapping',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Separate_Room_Swapping',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Soft_Swing',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Spanking',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Swingers_Clubs',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Taking_Photos',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Threesomes',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Toys',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Voyeurism',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Watersports',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='Webcams',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='adult_parties',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='blindfolds',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='cross_dressing',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='cuckolding',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='cybersex',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='dogging',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='fisting',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='gangbangs',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
