# Generated by Django 5.0.6 on 2024-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_remove_interest_anal_interest_anal_giving_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='Oral',
            new_name='Oral_giving_blowjob',
        ),
        migrations.AddField(
            model_name='interest',
            name='Oral_giving_pussy_licking',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='Oral_receiving',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
