# Generated by Django 5.0.6 on 2024-10-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_rename_oral_interest_oral_giving_blowjob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='Group_Sex',
            new_name='group_sex',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Making_Videos',
            new_name='making_videos',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Oral_giving_blowjob',
            new_name='oral_giving_blowjob',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Oral_giving_pussy_licking',
            new_name='oral_giving_pussy_licking',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Oral_receiving',
            new_name='oral_receiving',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Phone_Sex',
            new_name='phone_sex',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Rimming',
            new_name='rimming',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Role_Play',
            new_name='role_play',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Safe_Sex',
            new_name='safe_sex',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Same_Room_Swapping',
            new_name='same_room_swapping',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Separate_Room_Swapping',
            new_name='separate_room_swapping',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Soft_Swing',
            new_name='soft_swing',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Spanking',
            new_name='spanking',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Swingers_Clubs',
            new_name='swingers_clubs',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Taking_Photos',
            new_name='taking_photos',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Threesomes',
            new_name='threesomes',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Toys',
            new_name='toys',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Voyeurism',
            new_name='voyeurism',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Watersports',
            new_name='watersports',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='Webcams',
            new_name='webcams',
        ),
    ]
