# Generated by Django 5.0.6 on 2024-11-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0063_verifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifications',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
