# Generated by Django 5.0.6 on 2024-11-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0065_rename_verifications_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='verifyer',
        ),
        migrations.AddField(
            model_name='verification',
            name='user_verified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_verified', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
