# Generated by Django 5.0.6 on 2024-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0066_remove_verification_verifyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
