# Generated by Django 5.0.6 on 2024-08-23 14:03

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0015_alter_page_address1_alter_page_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_list', models.CharField(max_length=100)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='events')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.page')),
            ],
        ),
    ]
