# Generated by Django 5.0.6 on 2024-09-03 00:23

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('pages', '0015_alter_page_address1_alter_page_address2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_location', to='pages.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='private',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, quality=70, scale=None, size=[900, 900], upload_to='profile_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL),
        ),
    ]
