# Generated by Django 5.0.6 on 2024-09-03 00:54

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_description_events_location_events_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='host_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=70, scale=None, size=[900, 900], upload_to='profile_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='events',
            name='private',
            field=models.BooleanField(default=1),
        ),
    ]
