# Generated by Django 5.0.6 on 2024-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_host_list_alter_events_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.TextField(default='Event Title', max_length=250),
            preserve_default=False,
        ),
    ]
