# Generated by Django 5.0.6 on 2024-09-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
