# Generated by Django 5.0.6 on 2024-09-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_private'),
        ('pages', '0015_alter_page_address1_alter_page_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pages.page'),
        ),
    ]
