# Generated by Django 5.0.6 on 2024-09-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_additional_info_event_admission_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='opening_times',
        ),
    ]
