# Generated by Django 5.0.6 on 2024-09-09 20:41

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_opening_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='admission_fees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='private',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=70, scale=None, size=[900, 900], upload_to='event_images/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='EventDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('admission_fees', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_event', to='events.event')),
            ],
        ),
    ]
