# Generated by Django 5.0.6 on 2024-09-09 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventdates_admission_fees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDates',
            new_name='EventDate',
        ),
        migrations.RenameModel(
            old_name='EventReviews',
            new_name='EventReview',
        ),
    ]
