# Generated by Django 5.0.6 on 2024-09-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_eventdates_eventdate_and_more'),
        ('pages', '0019_pagehost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host_list',
        ),
        migrations.AddField(
            model_name='event',
            name='host_list',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='pages.pagehost'),
        ),
    ]
