# Generated by Django 5.0.6 on 2024-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_host_list_event_host_list'),
        ('pages', '0021_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_list',
            field=models.ManyToManyField(blank=True, max_length=100, to='pages.pagehost'),
        ),
    ]
