# Generated by Django 5.0.6 on 2024-10-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_host_list_alter_event_image'),
        ('pages', '0028_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_list',
            field=models.ManyToManyField(blank=True, max_length=100, to='pages.pagehost'),
        ),
    ]
