# Generated by Django 5.0.6 on 2024-10-09 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_host_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_list',
            field=models.ManyToManyField(blank=True, max_length=100, to=settings.AUTH_USER_MODEL),
        ),
    ]
