# Generated by Django 5.0.6 on 2024-10-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_event_host_list_event_host_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host_list',
        ),
    ]
