# Generated by Django 5.0.6 on 2024-07-03 20:22

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='parties')),
                ('organiser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='pages.page')),
            ],
        ),
    ]
