# Generated by Django 4.0 on 2024-06-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parties',
            old_name='user',
            new_name='page',
        ),
    ]
