# Generated by Django 4.0 on 2024-06-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_profile_page_alter_page_user'),
        ('parties', '0002_rename_user_parties_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='page',
        ),
        migrations.AddField(
            model_name='parties',
            name='organiser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='pages.page'),
            preserve_default=False,
        ),
    ]
