# Generated by Django 5.0.6 on 2024-08-18 11:44

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_usergallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[900, 900], upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
