# Generated by Django 5.0.6 on 2024-06-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_profile_page_alter_page_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='address2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='county',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('Swingers Club', 'Club'), ('Gay Sauna', 'Gay Sauna'), ('Adult Cinema', 'Cinema'), ('Online Shop', 'Online Shop')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='post_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='town_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
