# Generated by Django 5.0.6 on 2024-06-30 23:36

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_address1_page_address2_page_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='intro',
        ),
        migrations.AlterField(
            model_name='page',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[600, 200], upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[600, 600], upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='page',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
    ]
