# Generated by Django 5.0.6 on 2024-07-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_intro_alter_page_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='user',
            new_name='owner',
        ),
    ]
