# Generated by Django 5.0.6 on 2024-07-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagefollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageFollow',
        ),
    ]
