# Generated by Django 5.0.6 on 2024-07-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagefollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefollow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_followers', to='pages.page'),
        ),
    ]
