# Generated by Django 5.0.6 on 2024-07-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_user_page_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
