# Generated by Django 5.0.6 on 2024-07-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_owner_page_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
