# Generated by Django 5.0.6 on 2024-07-01 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_owner_id_page_owner'),
        ('profiles', '0027_profile_body_type_profile_body_type2_profile_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='profiles.profile'),
        ),
    ]
