# Generated by Django 5.0.6 on 2024-08-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pagereviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagereviews',
            old_name='review',
            new_name='text',
        ),
    ]
