# Generated by Django 5.0.6 on 2024-08-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_review_pagereviews_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagereviews',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='pagereviews',
            old_name='page',
            new_name='page_name',
        ),
    ]
