# Generated by Django 5.0.6 on 2024-08-11 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_user_pagereviews_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereviews',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
