# Generated by Django 5.0.6 on 2024-07-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_page_owner'),
        ('profiles', '0027_profile_body_type_profile_body_type2_profile_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('Swingers Club', 'Swingers Club'), ('Gay Sauna', 'Gay Sauna'), ('Adult Cinema', 'Cinema'), ('Online Shop', 'Online Shop')], max_length=15),
        ),
    ]
