# Generated by Django 5.0.6 on 2024-08-14 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pagereviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='page_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
