# Generated by Django 5.0.6 on 2024-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_page_page_created_page_page_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
