# Generated by Django 5.0.6 on 2024-08-22 11:08

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='address1',
            field=models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='county',
            field=models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='insta',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='post_code',
            field=models.CharField(max_length=10, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='town_city',
            field=models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='x_twitter',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
