# Generated by Django 5.0.6 on 2024-09-12 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_page_address1_alter_page_address2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(verbose_name='Validate your claim')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimant', to=settings.AUTH_USER_MODEL)),
                ('page_claimed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_page', to='pages.page')),
            ],
        ),
    ]
