# Generated by Django 5.0.6 on 2024-09-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_claimpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimpage',
            name='reason',
            field=models.TextField(verbose_name='Reason for your claim'),
        ),
    ]
