# Generated by Django 5.0.6 on 2024-09-18 12:15

import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_claimpage_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(pages.models.Page.custom_user), related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
