# Generated by Django 5.0.6 on 2024-07-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_user_id_alter_page_owner'),
        ('profiles', '0027_profile_body_type_profile_body_type2_profile_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.profile'),
        ),
    ]
