# Generated by Django 5.0.6 on 2024-09-19 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_page_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_for', to='pages.page')),
            ],
            options={
                'unique_together': {('host', 'page_name')},
            },
        ),
    ]
