# Generated by Django 5.0.6 on 2024-09-25 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_pagehost'),
        ('place_area', '0004_alter_region_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place_area.region'),
        ),
    ]
