# Generated by Django 5.0.6 on 2024-09-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_page_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('location2', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('pages.page',),
        ),
    ]
