# Generated by Django 5.0.6 on 2024-09-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
