# Generated by Django 5.0.6 on 2024-09-29 16:10

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_delete_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(default='me@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='show_email_button',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='page',
            name='show_phone_button',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='claimpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='insta',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='tiktok',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='page',
            name='x_twitter',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
