# Generated by Django 5.0.6 on 2024-07-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_page_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user_id',
        ),
    ]
