# Generated by Django 5.0.6 on 2024-10-06 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_page_email_page_lat_page_lon_page_show_email_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
