# Generated by Django 5.0.6 on 2024-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_page_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
