# Generated by Django 5.0.6 on 2024-07-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_page_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_name',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='owner',
            new_name='user',
        ),
    ]
