# Generated by Django 5.0.6 on 2024-07-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_page_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='user',
            new_name='owner',
        ),
    ]
