# Generated by Django 5.0.6 on 2024-10-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_page_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
