# Generated by Django 5.0.6 on 2024-07-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_rename_user_page_owner'),
        ('profiles', '0027_profile_body_type_profile_body_type2_profile_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
