# Generated by Django 5.0.6 on 2024-10-29 00:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_page_cover_image_alter_page_image'),
        ('place_area', '0011_alter_outerpostcode_postcode_alter_postcode_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='region',
        ),
        migrations.RemoveField(
            model_name='page',
            name='county',
        ),
        migrations.RemoveField(
            model_name='page',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='page',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='page',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='page',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='town_city',
        ),
        migrations.RemoveField(
            model_name='page',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='loc',
        ),
        migrations.CreateModel(
            name='CinemaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('address1', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('address2', models.CharField(blank=True, max_length=50, null=True, validators=[profanity.validators.validate_is_profane])),
                ('town_city', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('county', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('post_code', models.CharField(max_length=10, validators=[profanity.validators.validate_is_profane])),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place_area.region')),
            ],
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='ClubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('address1', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('address2', models.CharField(blank=True, max_length=50, null=True, validators=[profanity.validators.validate_is_profane])),
                ('town_city', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('county', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('post_code', models.CharField(max_length=10, validators=[profanity.validators.validate_is_profane])),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place_area.region')),
            ],
            bases=('pages.page',),
        ),
    ]
