# Generated by Django 5.0.6 on 2024-11-06 22:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_remove_page_region_remove_page_county_and_more'),
        ('place_area', '0011_alter_outerpostcode_postcode_alter_postcode_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.page')),
                ('address1', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('address2', models.CharField(blank=True, max_length=50, null=True, validators=[profanity.validators.validate_is_profane])),
                ('town_city', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('county', models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane])),
                ('post_code', models.CharField(max_length=10, validators=[profanity.validators.validate_is_profane])),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('num_rooms', models.IntegerField(null=True, verbose_name='Number of rooms')),
                ('ensuite', models.BooleanField(verbose_name='Ensuite rooms')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place_area.region')),
            ],
            bases=('pages.page',),
        ),
    ]
