# Generated by Django 5.0.6 on 2024-11-07 01:14

import django_resized.forms
import pages.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_hotelpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 200], upload_to=pages.models.PathAndRename('page_covers')),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[200, 200], upload_to=pages.models.PathAndRename('page_avatars')),
        ),
    ]
