# Generated by Django 5.0.6 on 2024-10-18 13:57

import django.db.models.deletion
import report.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0012_alter_message_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=models.SET(report.models.Report.custom_user), related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedPage',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.report')),
            ],
            bases=('report.report',),
        ),
        migrations.CreateModel(
            name='ReportedPhoto',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.report')),
                ('image_url', models.CharField(max_length=500)),
            ],
            bases=('report.report',),
        ),
        migrations.CreateModel(
            name='ReportedMessage',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.report')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_message', to='messaging.message')),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('report.report',),
        ),
        migrations.CreateModel(
            name='ReportedProfile',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.report')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('report.report',),
        ),
    ]
