# Generated by Django 5.0.6 on 2024-09-25 05:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headerImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 200], upload_to='blog_headers'),
        ),
    ]
