# Generated by Django 5.0.6 on 2024-09-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_catagory_rename_tags_tag_blog_slug_blog_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='headerImage',
            new_name='header_image',
        ),
    ]
