# Generated by Django 5.0.6 on 2024-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterevent',
            name='private',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
