# Generated by Django 5.0.6 on 2024-10-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_ot_mmcoouples_masterevent_ot_mmcouples'),
        ('profiles', '0062_rename_group_sex_interest_group_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_for', to='event.masterevent')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='profiles.profile')),
            ],
            options={
                'unique_together': {('host', 'event')},
            },
        ),
    ]
