# Generated by Django 5.0.6 on 2024-10-23 00:52

import django_resized.forms
import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_guestlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlist',
            name='profile_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 600], upload_to=event.models.PathAndRename('event_images/2024/10/23')),
        ),
        migrations.AlterField(
            model_name='event',
            name='admission_fees',
            field=models.TextField(default='Couples\t£\nSingle Males\t£\nSingle Females\t£\nTV/TS\t£', null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 600], upload_to=event.models.PathAndRename('event_images/2024/10/23')),
        ),
        migrations.AlterField(
            model_name='privateparty',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 600], upload_to=event.models.PathAndRename('event_images/2024/10/23')),
        ),
        migrations.AlterField(
            model_name='social',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=200, null=True, quality=-1, scale=None, size=[600, 600], upload_to=event.models.PathAndRename('event_images/2024/10/23')),
        ),
    ]
