# Generated by Django 5.0.6 on 2024-10-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_event_admission_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
