# Generated by Django 5.0.6 on 2024-11-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_meet_date_meet_end_time_meet_start_time'),
        ('pages', '0029_remove_page_region_remove_page_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pages.clubpage'),
        ),
    ]
