# Generated by Django 5.0.6 on 2024-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_clubevent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterevent',
            name='ot_ffcouples',
            field=models.BooleanField(blank=True, verbose_name='Open to FF Couples'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_men',
            field=models.BooleanField(blank=True, verbose_name='Open to Men'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_mfcouples',
            field=models.BooleanField(blank=True, verbose_name='Open to MF Couples'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_mmcouples',
            field=models.BooleanField(blank=True, verbose_name='Open to MM Couples'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_tvts',
            field=models.BooleanField(blank=True, verbose_name="Open to CD's and TV's"),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_women',
            field=models.BooleanField(blank=True, verbose_name='Open to Women'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='private',
            field=models.BooleanField(blank=True, verbose_name="Open to TG's and TS's"),
        ),
    ]
