# Generated by Django 5.0.6 on 2024-11-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_masterevent_ot_ffcouples_and_more'),
        ('pages', '0029_remove_page_region_remove_page_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_page', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='ot_tvts',
            field=models.BooleanField(blank=True, verbose_name='Open to CD-TV-TG-TS'),
        ),
        migrations.AlterField(
            model_name='masterevent',
            name='private',
            field=models.BooleanField(blank=True),
        ),
    ]
