# Generated by Django 5.0.6 on 2024-11-08 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_page_alter_masterevent_ot_tvts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlist',
            name='non_member',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
