# Generated by Django 5.0.6 on 2024-11-08 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_guestlist_non_member_alter_guestlist_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestlist',
            unique_together={('guest', 'non_member', 'event')},
        ),
    ]
