# Generated by Django 5.0.6 on 2024-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_guestlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='profile_type',
            field=models.CharField(choices=[('', 'Select Profile Type'), ('Man', 'Single Male'), ('Woman', 'Single Female'), ('CD/TV', 'CD_TV'), ('TV/TS', 'TV_TS'), ('Couple MF', 'Couple MF'), ('Couple FF', 'Couple FF'), ('Couple MM', 'Couple MM')], max_length=10, null=True),
        ),
    ]
