# Generated by Django 5.0.6 on 2024-12-03 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_guestlist_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
