# Generated by Django 4.0 on 2024-06-21 19:28

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='messages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Messages', to='auth.user')),
            ],
        ),
    ]
