# Generated by Django 5.0.6 on 2024-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_message_date_read_alter_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_read',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.TimeField(auto_now=True),
        ),
    ]
