# Generated by Django 5.0.6 on 2024-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_message_time_read_message_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(null=True),
        ),
    ]
