# Generated by Django 5.0.6 on 2024-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_read',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
