# Generated by Django 5.0.6 on 2024-07-04 04:47

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=10)),
                ('feature_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='feed_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
