# Generated by Django 5.0.6 on 2024-07-18 01:54

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_author_delete_pagepost'),
        ('pages', '0003_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='page_feed_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_posts', to='pages.page')),
            ],
        ),
    ]
