# Generated by Django 4.0 on 2024-06-15 07:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='feed_images'),
            preserve_default=False,
        ),
    ]
