# Generated by Django 5.0.6 on 2024-07-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_pagepost_author_alter_pagepost_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagepost',
            old_name='page',
            new_name='author',
        ),
    ]
