# Generated by Django 5.0.6 on 2024-07-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rename_page_pagepost_author'),
        ('pages', '0003_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='slug',
            field=models.SlugField(default=1, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_posts', to='pages.page'),
        ),
    ]
