# Generated by Django 5.0.6 on 2024-07-19 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_pagepost_slug_alter_pagepost_author'),
        ('pages', '0003_alter_page_cover_image_alter_page_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='feature_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_posts', to='pages.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
