# Generated by Django 5.0.6 on 2024-07-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_pagepost_feature_name_alter_pagepost_author'),
        ('pages', '0003_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepost',
            name='feature_name',
        ),
        migrations.AddField(
            model_name='pagepost',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.page'),
            preserve_default=False,
        ),
    ]
