# Generated by Django 5.0.6 on 2024-07-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_remove_pagepost_feature_name_pagepost_name'),
        ('pages', '0003_alter_page_cover_image_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_name', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='pagepost',
            name='slug',
            field=models.SlugField(verbose_name='name'),
        ),
    ]
