# Generated by Django 5.0.6 on 2024-07-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_pagepost_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature_type',
            new_name='post_type',
        ),
    ]
