# Generated by Django 5.0.6 on 2024-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_name',
            field=models.TextField(default='user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='feature_type',
            field=models.TextField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
