# Generated by Django 5.0.6 on 2024-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_post_feature_name_post_feature_type_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_type',
            field=models.CharField(max_length=10),
        ),
    ]
