# Generated by Django 5.0.6 on 2024-08-22 11:11

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_rename_pagelike_pagepostlike_rename_like_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='text',
            field=models.CharField(max_length=500, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=500, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
