# Generated by Django 5.0.6 on 2024-10-16 00:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_pagepost_text_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='page_feed_images'),
        ),
    ]
