# Generated by Django 5.0.6 on 2024-09-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=100),
        ),
    ]
