# Generated by Django 5.0.6 on 2024-09-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0002_alter_region_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
