# Generated by Django 5.0.6 on 2024-09-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0003_region_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region_name']},
        ),
    ]
