# Generated by Django 5.0.6 on 2024-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0004_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuterPoatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.TextField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
