# Generated by Django 5.0.6 on 2024-09-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0005_outerpoatcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OuterPoatCode',
            new_name='OuterPostCode',
        ),
    ]
