# Generated by Django 5.0.6 on 2024-09-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0006_rename_outerpoatcode_outerpostcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outerpostcode',
            old_name='postcode',
            new_name='outer_pc',
        ),
    ]
