# Generated by Django 5.0.6 on 2024-09-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0008_rename_outer_pc_outerpostcode_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outerpostcode',
            options={'ordering': ['postcode']},
        ),
    ]
