# Generated by Django 5.0.6 on 2024-10-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_area', '0010_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerpostcode',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
